CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role ENUM('Super Admin', 'Admin', 'Manager', 'Staff') NOT NULL,
  team VARCHAR(64) NOT NULL,
  teams_json JSON NOT NULL,
  modules_json JSON NOT NULL,
  status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
  initials VARCHAR(8) NOT NULL,
  last_active VARCHAR(64) NULL,
  avatar_url TEXT NULL,
  notification_settings_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_credentials (
  user_id VARCHAR(64) PRIMARY KEY,
  password_value VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  assignee VARCHAR(255) NOT NULL,
  team VARCHAR(64) NOT NULL,
  priority VARCHAR(32) NOT NULL,
  status VARCHAR(64) NOT NULL,
  due DATE NOT NULL,
  project VARCHAR(255) NULL,
  notes TEXT NULL,
  requires_approval BOOLEAN NOT NULL DEFAULT FALSE,
  approver VARCHAR(255) NULL,
  approval_status VARCHAR(64) NULL,
  approval_history_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  team VARCHAR(64) NOT NULL,
  owner VARCHAR(255) NOT NULL,
  status VARCHAR(64) NOT NULL,
  progress INT NOT NULL DEFAULT 0,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  milestones_json JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS state_snapshots (
  state_key VARCHAR(64) PRIMARY KEY,
  state_json LONGTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
